### ISSUE TITLE
Weird Despawn Bug

### ISSUE THREAD

**Issue by vizthex123** [IDGCaptainRussia94/Ophioid-Mod#1]
So I love the multiple phases, but the boss sometimes travels waaaayyy too far away from where you are, and the first time I summoned it it despawned because of that.

Can you fix this? Thankfully it's not expensive to re-make the item, but it is still annoying that this happens.

**Comment by IDGCaptainRussia94** [comment]
Oh snap I never noticed this Github issue! Yeah I knew about this one for a while now, but honestly forgot about it, will look into trying to cap the worm's speed a bit more (on top of making despawns a bit harder to happen)

**Comment by vizthex123** [comment]
Alright, thanks

**Comment by IDGCaptainRussia94** [comment]
Alrighty, I pushed out an update that caps the velocity a bit more, and more importantly-dampens movement and lessons despawning if the boss goes flying away too far from the player
This should help, let me know if it works out

**Comment by vizthex123** [comment]
Yes it's been fixed, thanks.

Sorry for taking a year to respond lol.
